language: python


matrix:
  include:
    - python: 2.7
      env:
        - TOX_ENV=py27
    - python: 2.7
      env:
        - TOX_ENV=pep8
    - python: 3.6
      env:
        - TOX_ENV=py36
    - python: 3.6
      env:
        - TOX_ENV=pep8
install:
  - pip install tox


script:
  - tox -e $TOX_ENV
